[nfs]
172.31.0.120 ansible_ssh_user='ec2-user'

[webservers]
172.31.10.232 ansible_ssh_user='ec2-user'
172.31.12.22 ansible_ssh_user='ec2-user'

[db]
172.31.5.156 ansible_ssh_user='ubuntu' 

[lb]
172.31.6.219 ansible_ssh_user='ubuntu'
